sonar.projectKey=lavishmakkar123_tipsy-alcohol-delivery
sonar.organization=lavishmakkar123

sonar.sources=Backend,Frontend/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/build/**

sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,Backend/tests/**
sonar.coverage.exclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,Backend/tests/**,Backend/db/**,Backend/eslint.config.js,Backend/jest.config.js,Frontend/vitest.config.ts,Frontend/src/test/**

sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info,Frontend/coverage/lcov.info
