services:
  mysql:
    image: mysql:8.0
    container_name: tipsy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    volumes:
      - tipsy-mysql-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-proot']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  tipsy-mysql-data:
